<?php
use Drupal\formatage_models\FormatageModelsThemes;
use Stephane888\Debug\debugLog;

/**
 *
 * @file
 * Primary module hooks for formatage models module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implement hook_preprocess_page
 */
function formatage_models_preprocess_page(&$variables)
{
	// $Markup = new Markup();
	// $Markup->__toString()
	if (! empty($variables['page']['content'])) {
		foreach ( $variables['page']['content'] as $block ) {
			if (is_array($block) && ! empty($block["#theme"]) && $block["#theme"] == 'block')
				FormatageModelsThemes::ReInjectLayoutInAnotherRegion($block["#block"], $variables);
		}
	}
	// dump($variables['page']['content']);
	// MdbootstrapWbu::wbupreprocess_page($variables);
}

/**
 * Implement hook_item_list__layouts
 */
function formatage_models_preprocess_item_list__layouts(&$vars)
{
	// debugLog::$max_depth = 6;
	// debugLog::kintDebugDrupal($vars['items'], 'formatage_models_preprocess_item_list__layouts');
}

/**
 * Implements hook_theme().
 */
function formatage_models_theme()
{
	return FormatageModelsThemes::getThemeHooks();
}

function formatage_models_preprocess_formatage_models_hero_thegem_18(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_header_thegem_01(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_single_blog(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_item_section(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_images_bg(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_services_sliders(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_titre(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_lmsg_call_toaction(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_service_icone(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_expert_solution(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_image_after_before(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_hero_slider_popup(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

function formatage_models_preprocess_formatage_models_simple_block(array &$variables)
{
	FormatageModelsThemes::ApplyAttributes($variables);
	FormatageModelsThemes::addLayoutEditBlock($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_galery_title(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_teaser_img_desc(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_blog_list(array &$variables)
{
	FormatageModelsThemes::ApplyAttributes($variables);
	FormatageModelsThemes::addLayoutEditBlock($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_article_header(array &$variables)
{
	FormatageModelsThemes::ApplyAttributes($variables);
	FormatageModelsThemes::addLayoutEditBlock($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_teaser(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_teaser_a_la_une(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_realisation_big(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_realisation_small(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}

/**
 *
 * @param array $variables
 */
function formatage_models_preprocess_formatage_models_bg_header(array &$variables)
{
	FormatageModelsThemes::addLayoutEditBlock($variables);
	FormatageModelsThemes::ApplyAttributes($variables);
}